# Generated by Django 4.2.7 on 2025-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
